on:
  push:

jobs:
  custom_java_action_trigger_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@4

      - name: Hello world
        uses: Sebastian94gonzalez/hello-world-javascript-action@main
        with: 
          who-to-greet: SEB

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"